package com.example.poketriv.PokeDex;

import com.example.poketriv.R;
import java.util.ArrayList;

/**
 * A class that represents the data of a pokedex
 * Has an ArrayList for each category of pokemon
 */
public class PokeDex{

    public static ArrayList<Pokemon> generation1 = new ArrayList<>();
    public static ArrayList<Pokemon> generation2 = new ArrayList<>();
    public static ArrayList<Pokemon> generation3 = new ArrayList<>();
    public static ArrayList<Pokemon> generation4 = new ArrayList<>();
    public static ArrayList<Pokemon> generation5 = new ArrayList<>();
    public static ArrayList<Pokemon> generation6 = new ArrayList<>();
    public static ArrayList<Pokemon> generation7 = new ArrayList<>();
    public static ArrayList<Pokemon> generation8 = new ArrayList<>();
    public static ArrayList<Pokemon> commonPokemon = new ArrayList<>();
    public static ArrayList<Pokemon> rarePokemon = new ArrayList<>();
    public static ArrayList<Pokemon> superRarePokemon = new ArrayList<>();
    public static ArrayList<Pokemon> ultraPokemon = new ArrayList<>();
    public static ArrayList<Pokemon> legendPokemon = new ArrayList<>();


    /**
     * A method that makes all pokemon
     */
    public void addAllPokemon() {
        new Pokemon("#001", "Bulbasaur", "Grass", "Poison", R.drawable.bulbasaur,1, "rare");
        new Pokemon("#002", "Ivysaur", "Grass", "Poison", R.drawable.ivysaur,1, "superrare");
        new Pokemon("#003", "Venusaur", "Grass", "Poison", R.drawable.venusaur,1, "ultra");
        new Pokemon("#004", "Charmander", "Fire", null, R.drawable.charmander,1, "rare");
        new Pokemon("#005", "Charmeleon", "Fire", null, R.drawable.charmeleon,1, "superrare");
        new Pokemon("#006", "Charizard", "Fire", "Flying", R.drawable.charizard, 1, "ultra");
        new Pokemon("#007", "Squirtle", "Water", null, R.drawable.squirtle, 1, "rare");
        new Pokemon("#008", "Wartortle", "Water", null, R.drawable.wartortle,1,"superrare");
        new Pokemon("#009", "Blastoise", "Water", null, R.drawable.blastoise,1, "ultra");
        new Pokemon("#010", "Caterpie", "Bug", null, R.drawable.caterpie,1, "common");
        new Pokemon("#011", "Metapod", "Bug", null, R.drawable.metapod,1, "common");
        new Pokemon("#012", "Butterfree", "Bug", "Flying", R.drawable.butterfree,1, "rare");
        new Pokemon("#013", "Weedle", "Bug", "Poison", R.drawable.weedle,1,"common");
        new Pokemon("#014", "Kakuna", "Bug", "Poison", R.drawable.kakuna,1,"common");
        new Pokemon("#015", "Beedrill", "Bug", "Poison", R.drawable.beedrill,1,"rare");
        new Pokemon("#016", "Pidgey", "Normal", "Flying", R.drawable.pidgey,1,"common");
        new Pokemon("#017", "Pidgeotto", "Normal", "Flying", R.drawable.pidgeotto,1,"rare");
        new Pokemon("#018", "Pidgeot", "Normal", "Flying", R.drawable.pidgeot,1,"superrare");
        new Pokemon("#019", "Rattata", "Normal", null, R.drawable.rattata,1,"common");
        new Pokemon("#020", "Raticate", "Normal", null, R.drawable.raticate,1,"rare");
        new Pokemon("#021", "Spearow", "Normal", "Flying", R.drawable.spearow,1,"common");
        new Pokemon("#022", "Fearow", "Normal", "Flying", R.drawable.fearow,1,"rare");
        new Pokemon("#023", "Ekans", "Poison", null, R.drawable.ekans,1,"common");
        new Pokemon("#024", "Arbok", "Poison", null, R.drawable.arbok,1,"rare");
        new Pokemon("#025", "Pikachu", "Electric", null, R.drawable.pikachu,1,"rare");
        new Pokemon("#026", "Raichu", "Electric", null, R.drawable.raichu,1,"ultra");
        new Pokemon("#027", "Sandshrew", "Ground", null, R.drawable.sandshrew,1,"common");
        new Pokemon("#028", "Sandslash", "Ground", null, R.drawable.sandslash,1,"rare");
        new Pokemon("#029", "Nidoran♀", "Poison", null, R.drawable.nidoranf,1,"common");
        new Pokemon("#030", "Nidorina", "Poison", null, R.drawable.nidorina,1,"rare");
        new Pokemon("#031", "Nidoqueen", "Poison", "Ground", R.drawable.nidoqueen,1,"superrare");
        new Pokemon("#032", "Nidoran♂", "Poison", null, R.drawable.nidoranm,1,"common");
        new Pokemon("#033", "Nidorino", "Poison", null, R.drawable.nidorino,1,"rare");
        new Pokemon("#034", "Nidoking", "Poison", "Ground", R.drawable.nidoking,1,"superrare");
        new Pokemon("#035", "Clefairy", "Fairy", null, R.drawable.clefairy,1,"rare");
        new Pokemon("#036", "Clefable", "Fairy", null, R.drawable.clefable,1,"superrare");
        new Pokemon("#037", "Vulpix", "Fire", null, R.drawable.vulpix,1,"rare");
        new Pokemon("#038", "Ninetales", "Fire", null, R.drawable.ninetales,1,"ultra");
        new Pokemon("#039", "Jigglypuff", "Normal", "Fairy", R.drawable.jigglypuff,1, "common");
        new Pokemon("#040", "Wigglytuff", "Normal", "Fairy", R.drawable.wigglytuff,1,"superrare");
        new Pokemon("#041", "Zubat", "Poison", "Flying", R.drawable.zubat,1,"common");
        new Pokemon("#042", "Golbat", "Poison", "Flying", R.drawable.golbat,1,"rare");
        new Pokemon("#043", "Oddish", "Grass", "Poison", R.drawable.oddish,1,"common");
        new Pokemon("#044", "Gloom", "Grass", "Poison", R.drawable.gloom,1,"rare");
        new Pokemon("#045", "Vileplume", "Grass", "Poison", R.drawable.vileplume,1,"superrare");
        new Pokemon("#046", "Paras", "Bug", "Grass", R.drawable.paras, 1,"common");
        new Pokemon("#047", "Parasect", "Bug", "Grass", R.drawable.parasect,1,"rare");
        new Pokemon("#048", "Venonat", "Bug", "Poison", R.drawable.venonat,1,"rare");
        new Pokemon("#049", "Venomoth", "Bug", "Poison", R.drawable.venomoth,1,"superrare");
        new Pokemon("#050", "Diglett", "Ground", null, R.drawable.diglett,1,"common");
        new Pokemon("#051", "Dugtrio", "Ground", null, R.drawable.dugtrio,1,"ultra");
        new Pokemon("#052", "Meowth", "Normal", null, R.drawable.meowth,1,"rare");
        new Pokemon("#053", "Persian", "Normal", null, R.drawable.persian,1,"ultra");
        new Pokemon("#054", "Psyduck", "Water", null, R.drawable.psyduck,1,"common");
        new Pokemon("#055", "Golduck", "Water", null, R.drawable.golduck,1,"superrare");
        new Pokemon("#056", "Mankey", "Fighting", null, R.drawable.mankey,1,"rare");
        new Pokemon("#057", "Primeape", "Fighting", null, R.drawable.primeape,1,"ultra");
        new Pokemon("#058", "Growlithe", "Fire", null, R.drawable.growlithe,1,"superrare");
        new Pokemon("#059", "Arcanine", "Fire", null, R.drawable.arcanine,1, "ultra");
        new Pokemon("#060", "Poliwag", "Water", null, R.drawable.poliwag,1,"common");
        new Pokemon("#061", "Poliwhirl", "Water", null, R.drawable.poliwhirl,1,"rare");
        new Pokemon("#062", "Poliwrath", "Water", "Fighting", R.drawable.poliwrath,1,"ultra");
        new Pokemon("#063", "Abra", "Psychic", null, R.drawable.abra,1,"common");
        new Pokemon("#064", "Kadabra", "Psychic", null, R.drawable.kadabra,1,"rare");
        new Pokemon("#065", "Alakazam", "Psychic", null, R.drawable.alakazam,1,"ultra");
        new Pokemon("#066", "Machop", "Fighting", null, R.drawable.machop,1,"rare");
        new Pokemon("#067", "Machoke", "Fighting", null, R.drawable.machoke,1,"superrare");
        new Pokemon("#068", "Machamp", "Fighting", null, R.drawable.machamp,1,"superrare");
        new Pokemon("#069", "Bellsprout", "Grass", "Poison", R.drawable.bellsprout,1,"common");
        new Pokemon("#070", "Weepinbell", "Grass", "Poison", R.drawable.weepinbell,1,"rare");
        new Pokemon("#071", "Victreebel", "Grass", "Poison", R.drawable.victreebel,1,"superrare");
        new Pokemon("#072", "Tentacool", "Water", "Poison", R.drawable.tentacool,1,"common");
        new Pokemon("#073", "Tentacruel", "Water", "Poison", R.drawable.tentacruel,1,"rare");
        new Pokemon("#074", "Geodude", "Rock", "Ground", R.drawable.geodude,1,"common");
        new Pokemon("#075", "Graveler", "Rock", "Ground", R.drawable.graveler,1,"rare");
        new Pokemon("#076", "Golem", "Rock", "Ground", R.drawable.golem,1,"ultra");
        new Pokemon("#077", "Ponyta", "Fire", null, R.drawable.ponyta,1,"rare");
        new Pokemon("#078", "Rapidash", "Fire", null, R.drawable.rapidash,1,"ultra");
        new Pokemon("#079", "Slowpoke", "Water", "Psychic", R.drawable.slowpoke,1,"common");
        new Pokemon("#080", "Slowbro", "Water", "Psychic", R.drawable.slowbro,1,"rare");
        new Pokemon("#081", "Magnemite", "Electric", "Steel", R.drawable.magnemite,1,"common");
        new Pokemon("#082", "Magneton", "Electric", "Steel", R.drawable.magneton,1,"rare");
        new Pokemon("#083", "Farfetch'd", "Normal", "Flying", R.drawable.farfetchd,1,"superrare");
        new Pokemon("#084", "Doduo", "Normal", "Flying", R.drawable.doduo,1,"common");
        new Pokemon("#085", "Dodrio", "Normal", "Flying", R.drawable.dugtrio,1,"rare");
        new Pokemon("#086", "Seel", "Water", null, R.drawable.seel,1,"rare");
        new Pokemon("#087", "Dewgong", "Water", "Ice", R.drawable.dewgong,1,"superrare");
        new Pokemon("#088", "Grimer", "Poison", null, R.drawable.grimer,1,"common");
        new Pokemon("#089", "Muk", "Poison", null, R.drawable.muk,1,"superrare");
        new Pokemon("#090", "Shellder", "Water", null, R.drawable.shellder,1,"common");
        new Pokemon("#091", "Cloyster", "Water", "Ice", R.drawable.cloyster,1,"superrare");
        new Pokemon("#092", "Gastly", "Ghost", "Poison", R.drawable.gastly,1,"common");
        new Pokemon("#093", "Haunter", "Ghost", "Poison", R.drawable.haunter,1,"rare");
        new Pokemon("#094", "Gengar", "Ghost", "Poison", R.drawable.gengar,1,"ultra");
        new Pokemon("095", "Onix", "Rock", "Ground", R.drawable.onix,1,"rare");
        new Pokemon("#096", "Drowzee", "Psychic", null, R.drawable.drowzee,1,"common");
        new Pokemon("#097", "Hypno", "Psychic", null, R.drawable.hypno,1,"superrare");
        new Pokemon("#098", "Krabby", "Water", null, R.drawable.krabby,1,"commmon");
        new Pokemon("#099", "Kingler", "Water", null, R.drawable.kingler,1,"ultra");
        new Pokemon("#100", "Voltorb", "Electric", null, R.drawable.voltorb,1,"rare");
        new Pokemon("#101", "Electrode", "Electric", null, R.drawable.electrode,1,"superrare");
        new Pokemon("#102", "Exeggcute", "Grass", "Psychic", R.drawable.exeggcute,1,"common");
        new Pokemon("#103", "Exeggutor", "Grass", "Psychic", R.drawable.exeggutor,1,"rare");
        new Pokemon("#104", "Cubone", "Ground", null, R.drawable.cubone,1,"rare");
        new Pokemon("#105", "Marowak", "Ground", null, R.drawable.marowak,1,"ultra");
        new Pokemon("#106", "Hitmonlee", "Fighting", null, R.drawable.hitmonlee,1, "ultra");
        new Pokemon("#107", "Hitmonchan", "Fighting", null, R.drawable.hitmonchan, 1,"ultra");
        new Pokemon("#108", "Lickitung", "Normal", null, R.drawable.lickitung,1,"rare");
        new Pokemon("#109", "Koffing", "Poison", null, R.drawable.koffing,1,"common");
        new Pokemon("#110", "Weezing", "Poison", null, R.drawable.weezing,1,"rare");
        new Pokemon("#111", "Rhyhorn", "Ground", "Rock", R.drawable.rhyhorn,1,"common");
        new Pokemon("#112", "Rhydon", "Ground", "Rock", R.drawable.rhydon,1,"superrare");
        new Pokemon("#113", "Chansey", "Normal", null, R.drawable.chansey,1,"rare");
        new Pokemon("#114", "Tangela", "Grass", null, R.drawable.tangela,1,"rare");
        new Pokemon("#115", "Kangaskhan", "Normal", null, R.drawable.kangaskhan,1,"superrare");
        new Pokemon("#116", "Horsea", "Water", null, R.drawable.horsea,1,"common");
        new Pokemon("#117", "Seadra", "Water", null, R.drawable.seadra,1,"rare");
        new Pokemon("#118", "Goldeen", "Water", null, R.drawable.goldeen,1,"common");
        new Pokemon("#119", "Seaking", "Water", null, R.drawable.seaking,1,"rare");
        new Pokemon("#120", "Staryu", "Water", null, R.drawable.staryu,1,"common");
        new Pokemon("#121", "Starmie", "Water", "Psychic", R.drawable.starmie,1,"superrare");
        new Pokemon("#122", "Mr.Mime", "Psychic", "Fairy", R.drawable.mrmime,1,"rare");
        new Pokemon("#123", "Scyther", "Bug", "Flying", R.drawable.scyther,1,"rare");
        new Pokemon("#124", "Jynx", "Ice", "Psychic", R.drawable.jynx,1,"rare");
        new Pokemon("#125", "Electabuzz", "Electric", null, R.drawable.electrabuzz,1,"superrare");
        new Pokemon("#126", "Magmar", "Fire", null, R.drawable.magmar,1,"superrare");
        new Pokemon("#127", "Pinsir", "Bug", null, R.drawable.pinsir,1,"rare");
        new Pokemon("#128", "Tauros", "Normal", null, R.drawable.tauros,1,"rare");
        new Pokemon("#129", "Magikarp", "Water", null, R.drawable.magikarp,1,"common");
        new Pokemon("#130", "Gyarados",	"Water", "Flying", R.drawable.gyarados,1,"ultra");
        new Pokemon("#131:", "Lapras", "Water", "Ice", R.drawable.lapras,1,"legend");
        new Pokemon("#132", "Ditto", "Normal", null, R.drawable.ditto,1,"rare");
        new Pokemon("#133", "Eevee", "Normal", null, R.drawable.eevee,1,"rare");
        new Pokemon("#134", "Vaporeon", "Water", null, R.drawable.vaporeon,1,"ultra");
        new Pokemon("#135", "Jolteon", "Electric", null, R.drawable.jolteon,1,"ultra");
        new Pokemon("#136", "Flareon", "Fire", null , R.drawable.flareon,1,"ultra");
        new Pokemon("#137", "Porygon", "Normal", null, R.drawable.porygon,1,"rare");
        new Pokemon("#138", "Omanyte", "Rock", "Water", R.drawable.omanyte,1,"superrare");
        new Pokemon("#139", "Omastar", "Rock", "Water", R.drawable.omaster,1,"ultra");
        new Pokemon("#140", "Kabuto", "Rock", "Water", R.drawable.kabuto,1,"superrare");
        new Pokemon("#141", "Kabutops", "Rock", "Water", R.drawable.kabutops,1,"ultra");
        new Pokemon("#142", "Aerodactyl", "Rock", "Flying", R.drawable.aerodactyl,1,"ultra");
        new Pokemon("#143", "Snorlax", "Normal", null, R.drawable.snorlax,1,"ultra");
        new Pokemon("#144", "Articuno", "Ice", "Flying", R.drawable.articuno,1,"legend");
        new Pokemon("#145", "Zapdos", "Electric",  "Flying", R.drawable.zapdos,1,"legend");
        new Pokemon("#146", "Moltres", "Fire", "Flying", R.drawable.moltres,1,"legend");
        new Pokemon("#147", "Dratini", "Dragon", null, R.drawable.dratini,1,"superrare");
        new Pokemon("#148", "Dragonair", "Dragon", null, R.drawable.dragonair,1, "ultra");
        new Pokemon("#149", "Dragonite", "Dragon", "Flying", R.drawable.dragonite,1,"legend");
        new Pokemon("#150", "Mewtwo", "Psychic", null, R.drawable.mewtwo,1, "legend");
        new Pokemon("#151", "Mew", "Psychic", null, R.drawable.mew,1,"legend");
        new Pokemon( "#152", "Chikorita", "Grass", null, R.drawable.chikorita, 2, "rare");
        new Pokemon("#153", "Bayleef", "Grass", null, R.drawable.bayleef, 2, "superrare");
        new Pokemon("154","Meganium", "Grass", null, R.drawable.meganium, 2, "ultra");
        new Pokemon("155", "Cyndaquil", "Fire", null, R.drawable.cyndaquil, 2, "rare");
        new Pokemon("156", "Quilava", "Fire", null, R.drawable.quilava, 2, "superrare");
        new Pokemon("157","Typhlosion","Fire", null, R.drawable.typhlosion, 2, "ultra");
        new Pokemon("158", "Totodile", "Water", null, R.drawable.totodile, 2, "rare");
        new Pokemon("159", "Croconaw",	"Water", null, R.drawable.croconaw, 2, "superrare");
        new Pokemon("160", "Feraligatr", "Water", null, R.drawable.feraligatr, 2, "ultra");
        new Pokemon("161", "Sentret", "Normal", null, R.drawable.sentret, 2, "common");
        new Pokemon("162", "Furret", "Normal", null, R.drawable.furret, 2, "rare");
        new Pokemon("163", "Hoothoot", "Normal", "Flying", R.drawable.hoothoot, 2,"common");
        new Pokemon("164", "Noctowl", "Normal", "Flying", R.drawable.noctowl, 2, "rare");
        new Pokemon("165", "Ledyba", "Bug", "Flying", R.drawable.ledyba, 2, "common");
        new Pokemon("166", "Ledian", "Bug", "Flying", R.drawable.ledian, 2, "rare");
        new Pokemon("167", "Spinarak", "Bug", "Poison", R.drawable.spinarak, 2, "common");
        new Pokemon("168","Ariados", "Bug", "Poison", R.drawable.ariados, 2, "rare");
        new Pokemon("169", "Crobat","Poison","Flying",R.drawable.crobat, 2, "ultra");
        new Pokemon("170","Chinchou", "Water", "Electric", R.drawable.chinchou, 2, "rare");
        new Pokemon("171", "Lanturn","Water","Electric",R.drawable.lanturn,2,"superrare");
        new Pokemon("172","Pichu","Electric", null, R.drawable.pichu, 2, "rare");
        new Pokemon("173","Cleffa","Fairy",null,R.drawable.cleffa, 2,"common");
        new Pokemon("174","Igglybuff","Normal","Fairy",R.drawable.igglybuff,2,"common");
        new Pokemon("175","Togepi","Fairy",null,R.drawable.togepi, 2,"rare");
        new Pokemon("176","Togetic","Fairy","Flying",R.drawable.togetic, 2,"superrare");
        new Pokemon("177","Natu","Psychic","Flying",R.drawable.natu,2,"rare");
        new Pokemon("178","Xatu","Psychic","Flying",R.drawable.xatu,2,"superrare");
        new Pokemon("179","Mareep","Electric", null, R.drawable.mareep,2,"common");
        new Pokemon("180","Flaaffy","Electric", null, R.drawable.flaaffy, 2,"rare");
        new Pokemon("181","Ampharos","Electric",null,R.drawable.ampharos,2,"ultra");
        new Pokemon("182","Bellossom","Grass",null,R.drawable.bellossom,2,"rare");
        new Pokemon("183","Marill","Water","Fairy",R.drawable.marill,2,"common");
        new Pokemon("184","Azumarill","Water","Fairy",R.drawable.azumarill,2,"superrare");
        new Pokemon("185","Sudowoodo","Rock",null,R.drawable.sudowoodo,2,"superrare");
        new Pokemon("186","Politoed","Water",null,R.drawable.politoed,2,"ultra");
        new Pokemon("187","Hoppip","Grass","Flying",R.drawable.hoppip,2,"common");
        new Pokemon("188","Skiploom","Grass","Flying",R.drawable.skiploom,2,"rare");
        new Pokemon("189","Jumpluff","Grass","Flying",R.drawable.jumpluff,2,"superrare");
        new Pokemon("190","Aipom","Normal",null,R.drawable.aipom,2,"rare");
        new Pokemon("191","Sunkern","Grass",null,R.drawable.sunkern,2,"common");
        new Pokemon("192","Sunflora","Grass",null,R.drawable.sunflora,2,"rare");
        new Pokemon("193","Yanma","Bug","Flying",R.drawable.yanma,2,"rare");
        new Pokemon("194","Wooper","Water","Ground",R.drawable.wooper,2,"common");
        new Pokemon("195","Quagsire","Water","Ground",R.drawable.quagsire,2,"superrare");
        new Pokemon("196","Espeon","Psychic",null,R.drawable.espeon,2,"ultra");
        new Pokemon("197","Umbreon","Dark",null,R.drawable.umbreon,2,"ultra");
        new Pokemon("198","Murkrow","Dark","Flying",R.drawable.murkrow,2,"common");
        new Pokemon("199","Slowking","Water","Psychic",R.drawable.slowking,2,"ultra");
        new Pokemon("200","Misdreavus","Ghost",null, R.drawable.misdreavus,2,"rare");
        new Pokemon("201","Unown","Psychic",null, R.drawable.unknown,2,"rare");
        new Pokemon("202","Wobbuffet","Psychic",null,R.drawable.wobbuffet,2,"superrare");
        new Pokemon("203","Girafarig","Normal","Psychic",R.drawable.girafarig,2,"superrare");
        new Pokemon("204","Pineco","Bug",null,R.drawable.pineco,2,"rare");
        new Pokemon("205","Forretress","Bug","Steel",R.drawable.forretress,2,"superrare");
        new Pokemon("206","Dunsparce",	"Normal",null,R.drawable.dunsparce,2,"common");
        new Pokemon("207","Gligar","Ground","Flying",R.drawable.gligar,2,"rare");
        new Pokemon("208","Steelix","Steel","Ground",R.drawable.steelix,2,"ultra");
        new Pokemon("209","Snubbull","Fairy",null,R.drawable.snubbull,2,"common");
        new Pokemon("210","Granbull","Fairy",null,R.drawable.granbull,2,"rare");
        new Pokemon("211","Qwilfish","Water","Poison",R.drawable.qwilfish,2,"common");
        new Pokemon("212","Scizor","Bug","Steel",R.drawable.scizor,2,"ultra");
        new Pokemon("213","Shuckle","Bug","Rock",R.drawable.shuckle,2,"common");
        new Pokemon("214","Heracross","Bug","Fighting",R.drawable.heracross,2,"superrare");
        new Pokemon("215","Sneasel","Dark","Ice",R.drawable.sneasel,2,"rare");
        new Pokemon("216","Teddiursa","Normal",null,R.drawable.teddiursa,2,"common");
        new Pokemon("217","Ursaring","Normal",null,R.drawable.ursaring,2,"ultra");
        new Pokemon("218","Slugma","Fire",null,R.drawable.slugma,2,"common");
        new Pokemon("219","Magcargo","Fire","Rock",R.drawable.magcargo,2,"superrare");
        new Pokemon("220","Swinub","Ice","Ground",R.drawable.swinub,2,"common");
        new Pokemon("221","Piloswine","Ice","Ground",R.drawable.piloswine,2,"rare");
        new Pokemon("222","Corsola","Water","Rock",R.drawable.corsola,2,"rare");
        new Pokemon("223","Remoraid","Water",null,R.drawable.remoraid,2,"common");
        new Pokemon("224","Octillery","Water",null,R.drawable.octillery,2,"superrare");
        new Pokemon("225","Delibird","Ice","Flying",R.drawable.delibird,2,"rare");
        new Pokemon("226","Mantine","Water","Flying",R.drawable.mantine,2,"rare");
        new Pokemon("227","Skarmory","Steel","Flying",R.drawable.skarmory,2,"superrare");
        new Pokemon("228","Houndour","Dark","Fire",R.drawable.houndour,2,"rare");
        new Pokemon("229","Houndoom","Dark","Fire",R.drawable.houndoom,2,"ultra");
        new Pokemon("230","Kingdra","Water","Dragon",R.drawable.kingdra,2,"ultra");
        new Pokemon("231","Phanpy","Ground",null,R.drawable.phanpy,2,"common");
        new Pokemon("232","Donphan","Ground",null,R.drawable.donphan,2,"superrare");
        new Pokemon("233","Porygon2","Normal",null,R.drawable.porygon2,2,"superrare");
        new Pokemon("234","Stantler","Normal",null,R.drawable.stantler,2,"rare");
        new Pokemon("235","Smeargle","Normal",null,R.drawable.smeargle,2,"common");
        new Pokemon("236","Tyrogue","Fighting",null,R.drawable.tyrogue,2,"common");
        new Pokemon("237","Hitmontop","Fighting",null,R.drawable.hitmontop,2,"ultra");
        new Pokemon("238","Smoochum","Ice","Psychic",R.drawable.smoochum,2,"common");
        new Pokemon("239","Elekid","Electric",null,R.drawable.elekid,2,"common");
        new Pokemon("240","Magby","Fire",null,R.drawable.magby,2,"common");
        new Pokemon("241","Miltank","Normal",null,R.drawable.miltank,2,"common");
        new Pokemon("242","Blissey", "Normal",null,R.drawable.blissey,2,"superrare");
        new Pokemon("243","Raikou","Electric",null,R.drawable.raikou,2,"legend");
        new Pokemon("244","Entei","Fire",null,R.drawable.entei,2,"legend");
        new Pokemon("245","Suicune", "Water",null,R.drawable.suicune,2,"legend");
        new Pokemon("246","Larvitar","Rock","Ground",R.drawable.larvitar,2,"rare");
        new Pokemon("247","Pupitar","Rock","Ground",R.drawable.pupitar,2,"superrare");
        new Pokemon("248","Tyranitar","Rock","Dark",R.drawable.tyranitar,2,"legend");
        new Pokemon("249","Lugia","Psychic","Flying",R.drawable.lugia,2,"legend");
        new Pokemon("250","Ho-Oh","Fire","Flying",R.drawable.hooh,2,"legend");
        new Pokemon("251","Celebi","Psychic","Grass",R.drawable.celebi,2,"legend");
        new Pokemon("252","Treecko","Grass",null,R.drawable.treecko,3,"rare");
        new Pokemon("253","Grovyle","Grass",null,R.drawable.grovyle,3,"superrare");
        new Pokemon("254","Sceptile","Grass",null,R.drawable.sceptile,3,"ultra");
        new Pokemon("255","Torchic","Fire",null,R.drawable.torchic,3,"rare");
        new Pokemon("256","Combusken","Fire","Fighting",R.drawable.combusken,3,"superrare");
        new Pokemon("257","Blaziken","Fire","Fighting",R.drawable.blaziken,3,"ultra");
        new Pokemon("258","Mudkip","Water",null,R.drawable.mudkip,3,"rare");
        new Pokemon("259","Marshtomp","Water","Ground",R.drawable.marshtomp,3,"superrare");
        new Pokemon("260","Swampert","Water","Ground",R.drawable.swampert,3,"ultra");
        new Pokemon("261","Poochyena","Dark",null,R.drawable.poochyena,3,"common");
        new Pokemon("262","Mightyena","Dark",null,R.drawable.mightyena,3,"superrare");
        new Pokemon("263","Zigzagoon",	"Normal",null,R.drawable.zigzagoon,3,"common");
        new Pokemon("264","Linoone","Normal",null,R.drawable.linoone,3,"rare");
        new Pokemon("265","Wurmple","Bug",null,R.drawable.wurmple,3,"common");
        new Pokemon("266","Silcoon","Bug",null,R.drawable.silcoon,3,"common");
        new Pokemon("267","Beautifly","Bug","Flying",R.drawable.beautiply,3,"rare");
        new Pokemon("268","Cascoon","Bug",null,R.drawable.cascoon,3,"common");
        new Pokemon("269","Dustox","Bug","Poison",R.drawable.dustox,3,"rare");
        new Pokemon("270","Lotad","Water","Grass",R.drawable.lotad,3,"common");
        new Pokemon("271","Lombre","Water","Grass",R.drawable.lombre,3,"rare");
        new Pokemon("272","Ludicolo","Water","Grass",R.drawable.ludicolo,3,"superrare");
        new Pokemon("273","Seedot","Grass",null,R.drawable.seedot,3,"common");
        new Pokemon("274","Nuzleaf","Grass","Dark",R.drawable.nuzleaf,3,"rare");
        new Pokemon("275","Shiftry","Grass","Dark",R.drawable.shiftry,3,"ultra");
        new Pokemon("276","Taillow","Normal","Flying",R.drawable.taillow,3,"common");
        new Pokemon("277","Swellow","Normal","Flying",R.drawable.swellow,3,"rare");
        new Pokemon("278","Wingull","Water","Flying",R.drawable.wingull,3,"common");
        new Pokemon("279","Pelipper","Water","Flying",R.drawable.pelipper,3,"rare");
        new Pokemon("280","Ralts","Psychic","Fairy",R.drawable.ralts,3,"common");
        new Pokemon("281","Kirlia","Psychic","Fairy",R.drawable.kirlia,3,"rare");
        new Pokemon("282","Gardevoir","Psychic","Fairy",R.drawable.gardevoir,3,"ultra");
        new Pokemon("283","Surskit","Bug","Water",R.drawable.surskit,3,"common");
        new Pokemon("284","Masquerain","Bug","Flying",R.drawable.masquerain,3,"rare");
        new Pokemon("285","Shroomish","Grass",null,R.drawable.shroomish,3,"common");
        new Pokemon("286","Breloom","Grass","Fighting",R.drawable.breloon,3,"superrare");
        new Pokemon("287","Slakoth","Normal",null,R.drawable.slakoth,3,"common");
        new Pokemon("288","Vigoroth","Normal",null,R.drawable.vigoroth,3,"rare");
        new Pokemon("289","Slaking","Normal",null,R.drawable.slaking,3,"ultra");
        new Pokemon("290","Nincada","Bug","Ground",R.drawable.nincada,3,"common");
        new Pokemon("291","Ninjask","Bug","Flying",R.drawable.ninjask,3,"superrare");
        new Pokemon("292","Shedinja","Bug","Ghost",R.drawable.shedinja,3,"superrare");
        new Pokemon("293","Whismur","Normal",null,R.drawable.whismur,3,"common");
        new Pokemon("294","Loudred","Normal",null,R.drawable.loudred,3,"rare");
        new Pokemon("295","Exploud","Normal",null,R.drawable.exploud,3,"ultra");
        new Pokemon("296","Makuhita","Fighting",null,R.drawable.makuhita,3,"common");
        new Pokemon("297","Hariyama","Fighting",null,R.drawable.hariyama,3,"superrare");
        new Pokemon("298","Azurill","Normal","Fairy",R.drawable.azurill,3,"common");
        new Pokemon("299","Nosepass","Rock",null,R.drawable.nosepass,3,"common");
        new Pokemon("300","Skitty","Normal",null,R.drawable.skitty,3,"common");
        new Pokemon("301","Delcatty","Normal",null,R.drawable.delcatty,3,"rare");
        new Pokemon("302","Sableye","Dark","Ghost",R.drawable.sableye,3,"superrare");
        new Pokemon("303","Mawile","Steel","Fairy",R.drawable.mawile,3,"rare");
        new Pokemon("304","Aron","Steel","Rock",R.drawable.aron,3,"common");
        new Pokemon("305","Lairon","Steel","Rock",R.drawable.lairon,3,"superrare");
        new Pokemon("306","Aggron","Steel","Rock",R.drawable.aggron,3,"ultra");
        new Pokemon("307","Meditite","Fighting","Psychic",R.drawable.meditite,3,"rare");
        new Pokemon("308","Medicham","Fighting","Psychic",R.drawable.medicham,3,"superrare");
        new Pokemon("309","Electrike","Electric",null,R.drawable.electrike,3,"common");
        new Pokemon("310","Manectric","Electric",null,R.drawable.manectric,3,"superrare");
        new Pokemon("311","Plusle","Electric",null,R.drawable.plusle,3,"rare");
        new Pokemon("312","Minun","Electric",null,R.drawable.minun,3,"rare");
        new Pokemon("313","Volbeat","Bug",null,R.drawable.volbeat,3,"rare");
        new Pokemon("314","Illumise","Bug",null,R.drawable.illumise,3,"rare");
        new Pokemon("315","Roselia","Grass","Poison",R.drawable.roselia,3,"rare");
        new Pokemon("316","Gulpin","Poison",null,R.drawable.gulpin,3,"common");
        new Pokemon("317","Swalot","Poison",null,R.drawable.swalot,3,"rare");
        new Pokemon("318","Carvanha","Water","Dark",R.drawable.carvanha,3,"common");
        new Pokemon("319","Sharpedo","Water","Dark",R.drawable.sharpedo,3,"superrare");
        new Pokemon("320","Wailmer","Water",null,R.drawable.wailmer,3,"rare");
        new Pokemon("321","Wailord","Water",null,R.drawable.waillord,3,"ultra");
        new Pokemon("322","Numel","Fire","Ground",R.drawable.numel,3,"common");
        new Pokemon("323","Camerupt","Fire","Ground",R.drawable.camerupt,3,"superrare");
        new Pokemon("324","Torkoal","Fire",null,R.drawable.torkoal,3,"superrare");
        new Pokemon("325","Spoink","Psychic",null,R.drawable.spoink,3,"common");
        new Pokemon("326","Grumpig","Psychic",null,R.drawable.grumpig,3,"rare");
        new Pokemon("327","Spinda","Normal",null,R.drawable.spinda,3,"common");
        new Pokemon("328","Trapinch","Ground",null,R.drawable.trapinch,3,"common");
        new Pokemon("329","Vibrava","Ground","Dragon",R.drawable.vibrava,3,"rare");
        new Pokemon("330","Flygon","Ground","Dragon",R.drawable.flygon,3,"ultra");
        new Pokemon("331","Cacnea","Grass",null,R.drawable.cacnea,3,"common");
        new Pokemon("332","Cacturne","Grass","Dark",R.drawable.cacturne,3,"superrare");
        new Pokemon("333","Swablu","Normal","Flying",R.drawable.swablu,3,"rare");
        new Pokemon("334","Altaria","Dragon","Flying",R.drawable.altaria,3,"ultra");
        new Pokemon("335","Zangoose","Normal",null,R.drawable.zangoose,3,"superrare");
        new Pokemon("336","Seviper","Poison",null,R.drawable.seviper,3,"superrare");
        new Pokemon("337","Lunatone","Rock","Psychic",R.drawable.lunatone,3,"rare");
        new Pokemon("338","Solrock","Rock","Psychic",R.drawable.solrock,3,"rare");
        new Pokemon("339","Barboach","Water","Ground",R.drawable.barboach,3,"common");
        new Pokemon("340","Whiscash","Water","Ground",R.drawable.whiscash,3,"rare");
        new Pokemon("341","Corphish","Water",null,R.drawable.corphish,3,"common");
        new Pokemon("342","Crawdaunt","Water","Dark",R.drawable.crawdaunt,3,"superrare");
        new Pokemon("343","Baltoy","Ground","Psychic",R.drawable.baltop,3,"rare");
        new Pokemon("344","Claydol","Ground","Psychic",R.drawable.claydol,3,"superrare");
        new Pokemon("345","Lileep","Rock","Grass",R.drawable.lileep,3,"rare");
        new Pokemon("346","Cradily","Rock","Grass",R.drawable.cradily,3,"ultra");
        new Pokemon("347","Anorith","Rock","Bug",R.drawable.anorith,3,"rare");
        new Pokemon("348","Armaldo","Rock","Bug",R.drawable.armaldo,3,"ultra");
        new Pokemon("349","Feebas","Water",null,R.drawable.feebas,3,"common");
        new Pokemon("350","Milotic","Water",null,R.drawable.milotic,3,"ultra");
        new Pokemon("351","Castform","Normal",null,R.drawable.castform,3,"common");
        new Pokemon("352","Kecleon","Normal",null,R.drawable.kecleon,3,"rare");
        new Pokemon("353","Shuppet","Ghost",null,R.drawable.shuppet,3,"common");
        new Pokemon("354","Banette","Ghost",null,R.drawable.banette,3,"superrare");
        new Pokemon("355","Duskull","Ghost",null,R.drawable.duskull,3,"common");
        new Pokemon("356","Dusclops","Ghost",null,R.drawable.dusclops,3,"rare");
        new Pokemon("357","Tropius","Grass","Flying",R.drawable.tropius,3,"superrare");
        new Pokemon("358","Chimecho","Psychic",null,R.drawable.chimecho,3,"superrare");
        new Pokemon("359","Absol","Dark",null,R.drawable.absol,3,"ultra");
        new Pokemon("360","Wynaut","Psychic",null,R.drawable.wynaut,3,"common");
        new Pokemon("361","Snorunt","Ice",null,R.drawable.snorunt,3,"common");
        new Pokemon("362","Glalie","Ice",null,R.drawable.glalie,3,"superrare");
        new Pokemon("363","Spheal","Ice","Water",R.drawable.spheal,3,"common");
        new Pokemon("364","Sealeo","Ice","Water",R.drawable.sealeo,3,"rare");
        new Pokemon("365","Walrein","Ice","Water",R.drawable.walrein,3,"ultra");
        new Pokemon("366","Clamperl","Water",null,R.drawable.clamperl,3,"rare");
        new Pokemon("367","Huntail","Water",null,R.drawable.huntail,3,"superrare");
        new Pokemon("368","Gorebyss","Water",null,R.drawable.gorebyss,3,"superrare");
        new Pokemon("369","Relicanth","Water","Rock",R.drawable.relicanth,3,"rare");
        new Pokemon("370","Luvdisc","Water",null,R.drawable.luvdisc,3,"common");
        new Pokemon("371","Bagon","Dragon",null,R.drawable.bagon,3,"rare");
        new Pokemon("372","Shelgon","Dragon",null,R.drawable.shelgon,3,"superrare");
        new Pokemon("373","Salamence","Dragon","Flying",R.drawable.salamence,3,"legend");
        new Pokemon("374","Beldum","Steel","Psychic",R.drawable.beldum,3,"rare");
        new Pokemon("375","Metang","Steel","Psychic",R.drawable.metang,3,"superrare");
        new Pokemon("376","Metagross","Steel","Psychic",R.drawable.metagross,3,"ultra");
        new Pokemon("377","Regirock","Rock",null,R.drawable.regirock,3,"legend");
        new Pokemon("378","Regice","Ice",null,R.drawable.regice,3,"legend");
        new Pokemon("379","Registeel","Steel",null,R.drawable.registeel,3,"legend");
        new Pokemon("380","Latias","Dragon","Psychic",R.drawable.latias,3,"legend");
        new Pokemon("381","Latios","Dragon","Psychic",R.drawable.latios,3,"legend");
        new Pokemon("382","Kyogre","Water",null,R.drawable.kyogre,3,"legend");
        new Pokemon("383","Groudon","Ground",null,R.drawable.groudon,3,"legend");
        new Pokemon("384","Rayquaza","Dragon","Flying",R.drawable.rayquaza,3,"legend");
        new Pokemon("385","Jirachi","Steel","Psychic",R.drawable.jirachi,3,"legend");
        new Pokemon("386","Deoxys","Psychic",null,R.drawable.deoxys,3,"legend");
        new Pokemon("387","Turtwig","Grass",null,R.drawable.turtwig,4,"rare");
        new Pokemon("388","Grotle","Grass",null,R.drawable.grotle,4,"superrare");
        new Pokemon("389","Torterra","Grass","Ground",R.drawable.torterra,4,"ultra");
        new Pokemon("390","Chimchar","Fire",null,R.drawable.chimchar,4,"rare");
        new Pokemon("391","Monferno","Fire","Fighting",R.drawable.monferno,4,"superrare");
        new Pokemon("392","Infernape","Fire","Fighting",R.drawable.infernape,4,"ultra");
        new Pokemon("393","Piplup","Water",null,R.drawable.piplup,4,"rare");
        new Pokemon("394","Prinplup","Water",null,R.drawable.prinplup,4,"superrare");
        new Pokemon("395","Empoleon","Water","Steel",R.drawable.empoleon,4,"ultra");
        new Pokemon("396","Starly","Normal","Flying",R.drawable.starly,4,"common");
        new Pokemon("397","Staravia","Normal","Flying",R.drawable.staravia,4,"rare");
        new Pokemon("398","Staraptor","Normal","Flying",R.drawable.staraptor,4,"superrare");
        new Pokemon("399","Bidoof","Normal",null,R.drawable.bidoof,4,"common");
        new Pokemon("400","Bibarel","Normal","Water",R.drawable.bibarel,4,"rare");
        new Pokemon("401","Kricketot", "Bug", null,R.drawable.kricketot,4,"common");
        new Pokemon("402","Kricketune","Bug",null,R.drawable.kricketune,4,"rare");
        new Pokemon("403","Shinx","Electric",null,R.drawable.shinx,4,"common");
        new Pokemon("404","Luxio","Electric",null,R.drawable.luxio,4,"rare");
        new Pokemon("405","Luxray","Electric",null,R.drawable.luxray,4,"superrare");
        new Pokemon("406","Budew","Grass","Poison",R.drawable.budew,4,"common");
        new Pokemon("407","Roserade","Grass","Poison",R.drawable.roserade,4,"superrare");
        new Pokemon("408","Cranidos","Rock",null,R.drawable.cranidos,4,"rare");
        new Pokemon("409","Rampardos","Rock",null,R.drawable.rampardos,4,"ultra");
        new Pokemon("410","Shieldon","Rock","Steel",R.drawable.shieldon,4,"rare");
        new Pokemon("411","Bastiodon","Rock","Steel",R.drawable.bastiodon,4,"ultra");
        new Pokemon("412","Burmy","Bug",null,R.drawable.burmy,4,"common");
        new Pokemon("413","Wormadam","Bug","Steel",R.drawable.wormadam,4,"common");
        new Pokemon("414","Mothim","Bug","Flying",R.drawable.mothim,4,"rare");
        new Pokemon("415","Combee","Bug","Flying",R.drawable.combee,4,"common");
        new Pokemon("416","Vespiquen","Bug","Flying",R.drawable.vesiquen,4,"rare");
        new Pokemon("417","Pachirisu","Electric",null,R.drawable.pachirisu,4,"common");
        new Pokemon("418","Buizel","Water",null,R.drawable.buizel,4,"common");
        new Pokemon("419","Floatzel","Water",null,R.drawable.floatzel,4,"superrare");
        new Pokemon("420","Cherubi","Grass",null,R.drawable.cherubi,4,"common");
        new Pokemon("421","Cherrim","Grass",null,R.drawable.cherrim,4,"rare");
        new Pokemon("422","Shellos","Water",null,R.drawable.shellos,4,"common");
        new Pokemon("423","Gastrodon","Water","Ground",R.drawable.gastrodon,4,"rare");
        new Pokemon("424","Ambipom","Normal",null,R.drawable.ambipom,4,"rare");
        new Pokemon("425","Drifloon","Ghost","Flying",R.drawable.drifloon,4,"common");
        new Pokemon("426","Drifblim","Ghost","Flying",R.drawable.drifblim,4,"superrare");
        new Pokemon("427","Buneary","Normal",null,R.drawable.buneary,4,"common");
        new Pokemon("428","Lopunny","Normal",null,R.drawable.lopunny,4,"rare");
        new Pokemon("429","Mismagius","Ghost",null,R.drawable.mismagius,4,"superrare");
        new Pokemon("430","Honchkrow","Dark","Flying",R.drawable.honchkrow,4,"superrare");
        new Pokemon("431","Glameow","Normal",null,R.drawable.glameow,4,"common");
        new Pokemon("432","Purugly","Normal",null,R.drawable.purugly,4,"superrare");
        new Pokemon("433","Chingling","Psychic",null,R.drawable.chingling,4,"common");
        new Pokemon("434","Stunky","Poison","Dark",R.drawable.stunky,4,"common");
        new Pokemon("435","Skuntank","Poison","Dark",R.drawable.skuntank,4,"superrare");
        new Pokemon("436","Bronzor","Steel","Psychic",R.drawable.bronzor,4,"rare");
        new Pokemon("437","Bronzong","Steel","Psychic",R.drawable.bronzong,4,"superrare");
        new Pokemon("438","Bonsly","Rock",null,R.drawable.bonsly,4,"common");
        new Pokemon("439","Mime Jr.","Psychic","Fairy",R.drawable.mimejr,4,"common");
        new Pokemon("440","Happiny","Normal",null,R.drawable.happiny,4,"common");
        new Pokemon("441","Chatot","Normal","Flying",R.drawable.chatot,4,"common");
        new Pokemon("442","Spiritomb","Ghost","Dark",R.drawable.spiritomb,4,"ultra");
        new Pokemon("443","Gible","Dragon","Ground",R.drawable.gible,4,"rare");
        new Pokemon("444","Gabite","Dragon","Ground",R.drawable.gabite,4,"superrare");
        new Pokemon("445","Garchomp","Dragon","Ground",R.drawable.garchomp,4,"legend");
        new Pokemon("446","Munchlax","Normal",null,R.drawable.munchlax,4,"common");
        new Pokemon("447","Riolu","Fighting",null,R.drawable.riolu,4,"rare");
        new Pokemon("448","Lucario","Fighting","Steel",R.drawable.lucario,4,"ultra");
        new Pokemon("449","Hippopotas","Ground",null,R.drawable.hippopotas,4,"common");
        new Pokemon("450","Hippowdon","Ground",null,R.drawable.hippowdon,4,"superrare");
        new Pokemon("451","Skorupi","Poison","Bug",R.drawable.skorupi,4,"rare");
        new Pokemon("452","Drapion","Poison","Dark",R.drawable.drapion,4,"ultra");
        new Pokemon("453","Croagunk","Poison","Fighting",R.drawable.croagunk,4,"rare");
        new Pokemon("454","Toxicroak","Poison","Fighting",R.drawable.toxicroak,4,"ultra");
        new Pokemon("455","Carnivine","Grass",null,R.drawable.carnivine,4,"rare");
        new Pokemon("456","Finneon","Water",null,R.drawable.finneon,4,"rare");
        new Pokemon("457","Lumineon","Water",null,R.drawable.lumineon,4,"superrare");
        new Pokemon("458","Mantyke","Water","Flying",R.drawable.mantyke,4,"rare");
        new Pokemon("459","Snover","Grass","Ice",R.drawable.snover,4,"common");
        new Pokemon("460","Abomasnow","Grass","Ice",R.drawable.abomasnow,4,"superrare");
        new Pokemon("461","Weavile","Dark","Ice",R.drawable.weavile,4,"superrare");
        new Pokemon("462","Magnezone","Electric","Steel",R.drawable.magnezone,4,"ultra");
        new Pokemon("463","Lickilicky","Normal",null,R.drawable.lickilicky,4,"rare");
        new Pokemon("464","Rhyperior","Ground","Rock",R.drawable.rhyperior,4,"ultra");
        new Pokemon("465","Tangrowth","Grass",null,R.drawable.tangrowth,4,"superrare");
        new Pokemon("466","Electivire","Electric",null,R.drawable.electivire,4,"ultra");
        new Pokemon("467","Magmortar","Fire",null,R.drawable.magmortar,4,"ultra");
        new Pokemon("468","Togekiss","Fairy","Flying",R.drawable.togekiss,4,"ultra");
        new Pokemon("469","Yanmega","Bug","Flying",R.drawable.yanmega,4,"superrare");
        new Pokemon("470","Leafeon","Grass",null,R.drawable.leafeon,4,"ultra");
        new Pokemon("471","Glaceon","Ice",null,R.drawable.glaceon,4,"ultra");
        new Pokemon("472","Gliscor","Ground","Flying",R.drawable.gliscor,4,"superrare");
        new Pokemon("473","Mamoswine","Ice","Ground",R.drawable.mamoswine,4,"ultra");
        new Pokemon("474","Porygon-Z","Normal",null,R.drawable.porygon3,4,"ultra");
        new Pokemon("475","Gallade","Psychic","Fighting",R.drawable.gallade,4,"ultra");
        new Pokemon("476","Probopass","Rock","Steel",R.drawable.probopass,4,"superrare");
        new Pokemon("477","Dusknoir","Ghost",null,R.drawable.dusknoir,4,"ultra");
        new Pokemon("478","Froslass","Ice","Ghost",R.drawable.froslass,4,"superrare");
        new Pokemon("479","Rotom","Electric","Ghost",R.drawable.rotom,4,"superrare");
        new Pokemon("480","Uxie","Psychic",null,R.drawable.uxie,4,"legend");
        new Pokemon("481","Mesprit","Psychic",null,R.drawable.mesprit,4,"legend");
        new Pokemon("482","Azelf","Psychic",null,R.drawable.azelf,4,"legend");
        new Pokemon("483","Dialga","Steel","Dragon",R.drawable.dialga,4,"legend");
        new Pokemon("484","Palkia","Water","Dragon",R.drawable.palkia,4,"legend");
        new Pokemon("485","Heatran","Fire","Steel",R.drawable.heatran,4,"legend");
        new Pokemon("486","Regigigas","Normal",null,R.drawable.regigigas,4,"legend");
        new Pokemon("487","Giratina","Ghost","Dragon",R.drawable.giratina,4,"legend");
        new Pokemon("488","Cresselia","Psychic",null,R.drawable.cresselia,4,"legend");
        new Pokemon("489","Phione","Water",null,R.drawable.phione,4,"legend");
        new Pokemon("490","Manaphy","Water",null,R.drawable.manaphy,4,"legend");
        new Pokemon("491","Darkrai","Dark",null,R.drawable.darkrai,4,"legend");
        new Pokemon("492","Shaymin","Grass","Flying",R.drawable.shaymin,4,"legend");
        new Pokemon("493","Arceus","Normal",null,R.drawable.arceus,4,"legend");
        new Pokemon("494","Victini","Psychic","Fire",R.drawable.victini,5,"legend");
        new Pokemon("495","Snivy","Grass",null,R.drawable.snivy,5,"rare");
        new Pokemon("496","Servine","Grass",null,R.drawable.servine,5,"superrare");
        new Pokemon("497","Serperior","Grass",null,R.drawable.serperior,5,"ultra");
        new Pokemon("498","Tepig","Fire",null,R.drawable.tepig,5,"rare");
        new Pokemon("499","Pignite","Fire","Fighting",R.drawable.pignite,5,"superrare");
        new Pokemon("500","Emboar","Fire","Fighting",R.drawable.emboar,5,"ultra");
        new Pokemon("501","Oshawott","Water",null,R.drawable.oshawott,5,"rare");
        new Pokemon("502","Dewott","Water",null,R.drawable.dewott,5,"superrare");
        new Pokemon("503","Samurott","Water",null,R.drawable.samurott,5,"ultra");
        new Pokemon("504","Patrat","Normal",null,R.drawable.patrat,5,"common");
        new Pokemon("505","Watchog","Normal",null,R.drawable.watchog,5,"rare");
        new Pokemon("506","Lillipup","Normal",null,R.drawable.lillipup,5,"common");
        new Pokemon("507","Herdier","Normal",null,R.drawable.herdier,5,"rare");
        new Pokemon("508","Stoutland","Normal",null,R.drawable.stoutland,5,"superrare");
        new Pokemon("509","Purrloin","Dark",null,R.drawable.purrloin,5,"common");
        new Pokemon("510","Liepard","Dark",null,R.drawable.liepard,5,"rare");
        new Pokemon("511","Pansage","Grass",null,R.drawable.pansage,5,"common");
        new Pokemon("512","Simisage","Grass",null,R.drawable.simisage,5,"rare");
        new Pokemon("513","Pansear","Fire",null,R.drawable.pansear,5,"common");
        new Pokemon("514","Simisear","Fire",null,R.drawable.simisear,5,"rare");
        new Pokemon("515","Panpour","Water",null,R.drawable.panpour,5,"common");
        new Pokemon("516","Simipour","Water",null,R.drawable.simipour,5,"rare");
        new Pokemon("517","Munna","Psychic",null,R.drawable.munna,5,"rare");
        new Pokemon("518","Musharna","Psychic",null,R.drawable.musharna,5,"superrare");
        new Pokemon("519","Pidove","Normal","Flying",R.drawable.pidove,5,"common");
        new Pokemon("520","Tranquill","Normal","Flying",R.drawable.tranquill,5,"rare");
        new Pokemon("521","Unfezant","Normal","Flying",R.drawable.unfezant,5,"superrare");
        new Pokemon("522","Blitzle","Electric",null,R.drawable.blitzle,5,"common");
        new Pokemon("523","Zebstrika","Electric",null,R.drawable.zebstrika,5,"superrare");
        new Pokemon("524","Roggenrola","Rock",null,R.drawable.roggenrola,5,"common");
        new Pokemon("525","Boldore","Rock",null,R.drawable.boldore,5,"rare");
        new Pokemon("526","Gigalith","Rock",null,R.drawable.gigalith,5,"ultra");
        new Pokemon("527","Woobat","Psychic","Flying",R.drawable.woobat,5,"common");
        new Pokemon("528","Swoobat","Psychic","Flying",R.drawable.swoobat,5,"rare");
        new Pokemon("529","Drilbur","Ground",null,R.drawable.drilbur,5,"common");
        new Pokemon("530","Excadrill","Ground","Steel",R.drawable.excadrill,5,"superrare");
        new Pokemon("531","Audino","Normal",null,R.drawable.audino,5,"rare");
        new Pokemon("532","Timburr","Fighting",null,R.drawable.timburr,5,"common");
        new Pokemon("533","Gurdurr","Fighting",null,R.drawable.gurdurr,5,"rare");
        new Pokemon("534","Conkeldurr","Fighting",null,R.drawable.conkeldurr,5,"ultra");
        new Pokemon("535","Tympole","Water",null,R.drawable.tympole,5,"common");
        new Pokemon("536","Palpitoad","Water","Ground",R.drawable.palpitoad,5,"rare");
        new Pokemon("537","Seismitoad","Water","Ground",R.drawable.seismitoad,5,"ultra");
        new Pokemon("538","Throh","Fighting",null,R.drawable.throh,5,"superrare");
        new Pokemon("539","Sawk","Fighting",null,R.drawable.sawk,5,"superrare");
        new Pokemon("540","Sewaddle","Bug","Grass",R.drawable.sewaddle,5,"common");
        new Pokemon("541","Swadloon","Bug","Grass",R.drawable.swadloon,5,"common");
        new Pokemon("542","Leavanny","Bug","Grass",R.drawable.leavanny,5,"rare");
        new Pokemon("543","Venipede","Bug","Poison",R.drawable.venipede,5,"common");
        new Pokemon("544","Whirlipede","Bu","Poison",R.drawable.whirlipede,5,"rare");
        new Pokemon("545","Scolipede","Bug","Poison",R.drawable.scolipede,5,"superrare");
        new Pokemon("546","Cottonee","Grass",null,R.drawable.cottonee,5,"common");
        new Pokemon("547","Whimsicott","Grass","Fairy",R.drawable.whimsicott,5,"rare");
        new Pokemon("548","Petilil","Grass",null,R.drawable.petilil,5,"common");
        new Pokemon("549","Lilligant", "Grass",null,R.drawable.lilligant,5,"rare");
        new Pokemon("550","Basculin","Water",null,R.drawable.basculin,5,"common");
        new Pokemon("551","Sandile","Ground","Dark",R.drawable.sandile,5,"common");
        new Pokemon("552","Krokorok","Ground","Dark",R.drawable.krokorok,5,"rare");
        new Pokemon("553","Krookodile","Ground","Dark",R.drawable.krookodile,5,"ultra");
        new Pokemon("554","Darumaka","Fire",null,R.drawable.darumaka,5,"common");
        new Pokemon("555","Darmanitan","Fire",null,R.drawable.darmanitan,5,"superrare");
        new Pokemon("556","Maractus","Grass",null,R.drawable.maractus,5,"rare");
        new Pokemon("557","Dwebble","Bug","Rock",R.drawable.dwebble,5,"common");
        new Pokemon("558","Crustle","Bug","Rock",R.drawable.crustle,5,"superrare");
        new Pokemon("559","Scraggy","Dark","Fighting",R.drawable.scraggy,5,"common");
        new Pokemon("560","Scrafty","Dark","Fighting",R.drawable.scrafty,5,"superrare");
        new Pokemon("561","Sigilyph","Psychic","Flying",R.drawable.sigilyph,5,"superrare");
        new Pokemon("562","Yamask","Ghost",null,R.drawable.yamask,5,"common");
        new Pokemon("563","Cofagrigus","Ghost",null,R.drawable.cofagrigus,5,"superrare");
        new Pokemon("564","Tirtouga","Water","Rock",R.drawable.tirtouga,5,"rare");
        new Pokemon("565","Carracosta","Water","Rock",R.drawable.carracosta,5,"ultra");
        new Pokemon("566","Archen","Rock","Flying",R.drawable.archen,5,"rare");
        new Pokemon("567","Archeops","Rock","Flying",R.drawable.archeops,5,"ultra");
        new Pokemon("568","Trubbish","Poison",null,R.drawable.trubbish,5,"common");
        new Pokemon("569","Garbodor","Poison",null,R.drawable.garbodor,5,"superrare");
        new Pokemon("570","Zorua","Dark",null,R.drawable.zorua,5,"superrare");
        new Pokemon("571","Zoroark","Dark",null,R.drawable.zoroark,5,"legend");
        new Pokemon("572","Minccino","Normal",null,R.drawable.minccino,5,"common");
        new Pokemon("573","Cinccino","Normal",null,R.drawable.cinccino,5,"rare");
        new Pokemon("574","Gothita","Psychic",null,R.drawable.gothita,5,"common");
        new Pokemon("575","Gothorita","Psychic",null,R.drawable.gothorita,5,"rare");
        new Pokemon("576","Gothitelle","Psychic",null,R.drawable.gothitelle,5,"ultra");
        new Pokemon("577","Solosis","Psychic",null,R.drawable.solosis,5,"common");
        new Pokemon("578","Duosion","Psychic",null,R.drawable.duosion,5,"rare");
        new Pokemon("579","Reuniclus","Psychic",null,R.drawable.reuniclus,5,"superrare");
        new Pokemon("580","Ducklett","Water","Flying",R.drawable.ducklett,5,"common");
        new Pokemon("581","Swanna","Water","Flying",R.drawable.swanna,5,"rare");
        new Pokemon("582","Vanillite","Ice",null,R.drawable.vanillite,5,"common");
        new Pokemon("583","Vanillish","Ice",null,R.drawable.vanillish,5,"rare");
        new Pokemon("584","Vanilluxe","Ice",null,R.drawable.vanilluxe,5,"superrare");
        new Pokemon("585","Deerling","Normal","Grass",R.drawable.deerling,5,"common");
        new Pokemon("586","Sawsbuck","Normal","Grass",R.drawable.sawsbuck,5,"rare");
        new Pokemon("587","Emolga","Electric","Flying",R.drawable.emolga,5,"rare");
        new Pokemon("588","Karrablast","Bug",null,R.drawable.karrablast,5,"common");
        new Pokemon("589","Escavalier","Bug","Steel",R.drawable.escavalier,5,"superrare");
        new Pokemon("590","Foongus","Grass","Poison",R.drawable.foongus,5,"common");
        new Pokemon("591","Amoonguss","Grass","Poison",R.drawable.amoonguss,5,"rare");
        new Pokemon("592","Frillish","Water","Ghost",R.drawable.frillish,5,"common");
        new Pokemon("593","Jellicent","Water","Ghost",R.drawable.jellicent,5,"superrare");
        new Pokemon("594","Alomomola","Water",null,R.drawable.alomomola,5,"rare");
        new Pokemon("595","Joltik","Bug","Electric",R.drawable.joltik,5,"common");
        new Pokemon("596","Galvantula","Bug","Electric",R.drawable.galvantula,5,"rare");
        new Pokemon("597","Ferroseed","Grass","Steel",R.drawable.ferroseed,5,"common");
        new Pokemon("598","Ferrothorn","Grass","Steel",R.drawable.ferrothorn,5,"superrare");
        new Pokemon("599","Klink","Steel",null,R.drawable.klink,5,"common");
        new Pokemon("600","Klang","Steel",null,R.drawable.klang,5,"rare");
        new Pokemon("601","Klinklang","Steel",null,R.drawable.klinklang,5,"ultra");
        new Pokemon("602","Tynamo","Electric",null,R.drawable.tynamo,5,"common");
        new Pokemon("603","Eelektrik","Electric",null,R.drawable.eelektrik,5,"rare");
        new Pokemon("604","Eelektross","Electric",null,R.drawable.eelektross,5,"ultra");
        new Pokemon("605","Elgyem","Psychic",null,R.drawable.elgyem,5,"rare");
        new Pokemon("606","Beheeyem","Psychic",null,R.drawable.beheeyem,5,"superrare");
        new Pokemon("607","Litwick","Ghost","Fire",R.drawable.litwick,5,"common");
        new Pokemon("608","Lampent","Ghost","Fire",R.drawable.lampent,5,"rare");
        new Pokemon("609","Chandelure","Ghost","Fire",R.drawable.chandelure,5,"ultra");
        new Pokemon("610","Axew","Dragon",null,R.drawable.axew,5,"rare");
        new Pokemon("611","Fraxure","Dragon",null,R.drawable.fraxure,5,"superrare");
        new Pokemon("612","Haxorus","Dragon",null,R.drawable.haxorus,5,"legend");
        new Pokemon("613","Cubchoo","Ice",null,R.drawable.cubchoo,5,"common");
        new Pokemon("614","Beartic","Ice",null,R.drawable.beartic,5,"ultra");
        new Pokemon("615","Cryogonal","Ice",null,R.drawable.cryogonal,5,"superrare");
        new Pokemon("616","Shelmet","Bug",null,R.drawable.shelmet,5,"common");
        new Pokemon("617","Accelgor","Bug",null,R.drawable.accelgor,5,"superrare");
        new Pokemon("618","Stunfisk","Ground","Electric",R.drawable.stunfisk,5,"common");
        new Pokemon("619","Mienfoo","Fighting",null,R.drawable.mienfoo,5,"rare");
        new Pokemon("620","Mienshao","Fighting",null,R.drawable.mienshao,5,"superrare");
        new Pokemon("621","Druddigon","Dragon",null,R.drawable.druddigon,5,"ultra");
        new Pokemon("622","Golett","Ground","Ghost",R.drawable.golett,5,"rare");
        new Pokemon("623","Golurk","Ground","Ghost",R.drawable.golurk,5,"ultra");
        new Pokemon("624","Pawniard","Dark","Steel",R.drawable.pawniard,5,"common");
        new Pokemon("625","Bisharp","Dark","Steel",R.drawable.bisharp,5,"superrare");
        new Pokemon("626","Bouffalant","Normal",null,R.drawable.bouffalant,5,"superrare");
        new Pokemon("627","Rufflet","Normal","Flying",R.drawable.rufflet,5,"common");
        new Pokemon("628","Braviary","Normal","Flying",R.drawable.braviary,5,"superrare");
        new Pokemon("629","Vullaby","Dark","Flying",R.drawable.vullaby,5,"common");
        new Pokemon("630","Mandibuzz","Dark","Flying",R.drawable.manibuzz,5,"rare");
        new Pokemon("631","Heatmor","Fire",null,R.drawable.heatmor,5,"superrare");
        new Pokemon("632","Durant","Bug","Steel",R.drawable.durant,5,"rare");
        new Pokemon("633","Deino","Dark","Dragon",R.drawable.deino,5,"common");
        new Pokemon("634","Zweilous","Dark","Dragon",R.drawable.zweilous,5,"rare");
        new Pokemon("635","Hydreigon","Dark","Dragon",R.drawable.hydreigon,5,"ultra");
        new Pokemon("636","Larvesta","Bug","Fire",R.drawable.larvesta,5,"rare");
        new Pokemon("637","Volcarona","Bug","Fire",R.drawable.volcarona,5,"legend");
        new Pokemon("638","Cobalion","Steel","Fighting",R.drawable.cobalion,5,"legend");
        new Pokemon("639","Terrakion","Rock","Fighting",R.drawable.terrakion,5,"legend");
        new Pokemon("640","Virizion","Grass","Fighting",R.drawable.virizion,5,"legend");
        new Pokemon("641","Tornadus","Flying",null,R.drawable.tornadus,5,"legend");
        new Pokemon("642","Thundurus","Electric","Flying",R.drawable.thundurus,5,"legend");
        new Pokemon("643","Reshiram","Dragon","Fire",R.drawable.reshiram,5,"legend");
        new Pokemon("644","Zekrom","Dragon","Electric",R.drawable.zekrom,5,"legend");
        new Pokemon("645","Landorus","Ground","Flying",R.drawable.landorus,5,"legend");
        new Pokemon("646","Kyurem","Dragon","Ice",R.drawable.kyurem,5,"legend");
        new Pokemon("647","Keldeo","Water","Fighting",R.drawable.keldeo,5,"legend");
        new Pokemon("648","Meloetta","Normal","Psychic",R.drawable.meloetta,5,"legend");
        new Pokemon("649","Genesect","Bug","Steel",R.drawable.genesect,5,"legend");
        new Pokemon("650","Chespin","Grass",null,R.drawable.chespin,6,"rare");
        new Pokemon("651","Quilladin","Grass",null,R.drawable.quilladin,6,"superrare");
        new Pokemon("652","Chesnaught","Grass","Fighting",R.drawable.chesnaught,6,"ultra");
        new Pokemon("653","Fennekin","Fire",null,R.drawable.fennekin,6,"rare");
        new Pokemon("654","Braixen","Fire",null,R.drawable.braixen,6,"superrare");
        new Pokemon("655","Delphox","Fire","Psychic",R.drawable.delphox,6,"ultra");
        new Pokemon("656","Froakie","Water",null,R.drawable.froakie,6,"rare");
        new Pokemon("657","Frogadier","Water",null,R.drawable.frogadier,6,"superrare");
        new Pokemon("658","Greninja","Water","Dark",R.drawable.greninja,6,"ultra");
        new Pokemon("659","Bunnelby","Normal",null,R.drawable.bunnelby,6,"common");
        new Pokemon("660","Diggersby","Normal","Ground",R.drawable.diggersby,6,"rare");
        new Pokemon("661","Fletchling","Normal","Flying",R.drawable.fletchling,6,"common");
        new Pokemon("662","Fletchinder","Fire","Flying",R.drawable.fletchinder,6,"rare");
        new Pokemon("663","Talonflame","Fire","Flying",R.drawable.talonflame,6,"superrare");
        new Pokemon("664","Scatterbug","Bug",null,R.drawable.scatterbug,6,"common");
        new Pokemon("665","Spewpa","Bug",null,R.drawable.spewpa,6,"common");
        new Pokemon("666","Vivillon","Bug","Flying",R.drawable.vivillon,6,"rare");
        new Pokemon("667","Litleo","Fire","Normal",R.drawable.litleo,6,"common");
        new Pokemon("668","Pyroar","Fire","Normal",R.drawable.pyroar,6,"superrare");
        new Pokemon("669","Flabébé","Fairy",null,R.drawable.flabebe,6,"common");
        new Pokemon("670","Floette","Fairy",null,R.drawable.floette,6,"rare");
        new Pokemon("671","Florges","Fairy",null,R.drawable.florges,6,"superrare");
        new Pokemon("672","Skiddo","Grass",null,R.drawable.skiddo,6,"common");
        new Pokemon("673","Gogoat","Grass",null,R.drawable.gogoat,6,"rare");
        new Pokemon("674","Pancham","Fighting",null,R.drawable.pancham,6,"common");
        new Pokemon("675","Pangoro","Fighting","Dark",R.drawable.pangoro,6,"superrare");
        new Pokemon("676","Furfrou","Normal",null,R.drawable.furfrou,6,"rare");
        new Pokemon("677","Espurr","Psychic",null,R.drawable.espurr,6,"common");
        new Pokemon("678","Meowstic","Psychic",null,R.drawable.meowstic,6,"rare");
        new Pokemon("679","Honedge","Steel","Ghost",R.drawable.honedge,6,"common");
        new Pokemon("680","Doublade","Steel","Ghost",R.drawable.doublade,6,"rare");
        new Pokemon("681","Aegislash","Steel","Ghost",R.drawable.aegislash,6,"ultra");
        new Pokemon("682","Spritzee","Fairy",null,R.drawable.spritzee,6,"common");
        new Pokemon("683","Aromatisse","Fairy",null,R.drawable.aromatisse,6,"rare");
        new Pokemon("684","Swirlix","Fairy",null,R.drawable.swirlix,6,"common");
        new Pokemon("685","Slurpuff","Fairy",null,R.drawable.slurpuff,6,"rare");
        new Pokemon("686","Inkay","Dark","Psychic",R.drawable.inkay,6,"common");
        new Pokemon("687","Malamar","Dark","Psychic",R.drawable.malamar,6,"superrare");
        new Pokemon("688","Binacle","Rock","Water",R.drawable.binacle,6,"common");
        new Pokemon("689","Barbaracle","Rock","Water",R.drawable.barbaracle,6,"ultra");
        new Pokemon("690","Skrelp","Poison","Water",R.drawable.skrelp,6,"common");
        new Pokemon("691","Dragalge","Poison","Dragon",R.drawable.dragalge,6,"superrare");
        new Pokemon("692","Clauncher","Water",null,R.drawable.clauncher,6,"common");
        new Pokemon("693","Clawitzer","Water",null,R.drawable.clawitzer,6,"rare");
        new Pokemon("694","Helioptile","Electric","Normal",R.drawable.helioptile,6,"common");
        new Pokemon("695","Heliolisk","Electric","Normal",R.drawable.heliolisk,6,"rare");
        new Pokemon("696","Tyrunt","Rock","Dragon",R.drawable.tyrunt,6,"rare");
        new Pokemon("697","Tyrantrum","Rock","Dragon",R.drawable.tyrantrum,6,"ultra");
        new Pokemon("698","Amaura","Rock","Ice",R.drawable.amaura,6,"rare");
        new Pokemon("699","Aurorus","Rock","Ice",R.drawable.aurorus,6,"ultra");
        new Pokemon("700","Sylveon","Fairy",null,R.drawable.sylveon,6,"ultra");
        new Pokemon("701","Hawlucha","Fighting","Flying",R.drawable.hawlucha,6,"superrare");
        new Pokemon("702","Dedenne","Electric","Fairy",R.drawable.dedenne,6,"common");
        new Pokemon("703","Carbink","Rock","Fairy",R.drawable.carbink,6,"rare");
        new Pokemon("704","Goomy","Dragon",null,R.drawable.goomy,6,"rare");
        new Pokemon("705","Sliggoo","Dragon",null,R.drawable.sliggoo,6,"superrare");
        new Pokemon("706","Goodra","Dragon",null,R.drawable.goodra,6,"ultra");
        new Pokemon("707","Klefki","Steel","Fairy",R.drawable.klefki,6,"rare");
        new Pokemon("708","Phantump","Ghost","Grass",R.drawable.phantump,6,"common");
        new Pokemon("709","Trevenant","Ghost","Grass",R.drawable.trevenant,6,"superrare");
        new Pokemon("710","Pumpkaboo","Ghost","Grass",R.drawable.pumpkaboo,6,"common");
        new Pokemon("711","Gourgeist","Ghost","Grass",R.drawable.gourgeist,6,"rare");
        new Pokemon("712","Bergmite","Ice",null,R.drawable.bergmite,6,"rare");
        new Pokemon("713","Avalugg","Ice",null,R.drawable.avalugg,6,"ultra");
        new Pokemon("714","Noibat","Flying","Dragon",R.drawable.noibat,6,"rare");
        new Pokemon("715","Noivern","Flying","Dragon",R.drawable.noivern,6,"ultra");
        new Pokemon("716","Xerneas","Fairy",null,R.drawable.xerneas,6,"legend");
        new Pokemon("717","Yveltal","Dark","Flying",R.drawable.yveltal,6,"legend");
        new Pokemon("718","Zygarde","Dragon","Ground",R.drawable.zygarde,6,"legend");
        new Pokemon("719","Diancie","Rock","Fairy",R.drawable.diancie,6,"legend");
        new Pokemon("720","Hoopa","Psychic","Ghost",R.drawable.hoopa,6,"legend");
        new Pokemon("721","Volcanion","Fire","Water",R.drawable.volcanion,6,"legend");
        new Pokemon("722","Rowlet","Grass","Flying",R.drawable.rowlet,7,"rare");
        new Pokemon("723","Dartrix","Grass","Flying",R.drawable.dartrix,7,"superrare");
        new Pokemon("724","Decidueye","Grass","Ghost",R.drawable.decidueye,7,"ultra");
        new Pokemon("725","Litten","Fire",null,R.drawable.litten,7,"rare");
        new Pokemon("726","Torracat","Fire",null,R.drawable.torracat,7,"superrare");
        new Pokemon("727","Incineroar","Fire","Dark",R.drawable.incineroar,7,"ultra");
        new Pokemon("728","Popplio","Water",null,R.drawable.popplio,7,"rare");
        new Pokemon("729","Brionne","Water",null,R.drawable.brionne,7,"superrare");
        new Pokemon("730","Primarina","Water","Fairy",R.drawable.primarina,7,"ultra");
        new Pokemon("731","Pikipek","Normal","Flying",R.drawable.pikipek,7,"common");
        new Pokemon("732","Trumbeak","Normal","Flying",R.drawable.trumbeak,7,"rare");
        new Pokemon("733","Toucannon","Normal","Flying",R.drawable.toucannon,7,"superrare");
        new Pokemon("734","Yungoos","Normal",null,R.drawable.yungoos,7,"common");
        new Pokemon("735","Gumshoos","Normal",null,R.drawable.gumshoos,7,"rare");
        new Pokemon("736","Grubbin","Bug",null,R.drawable.grubbin,7,"common");
        new Pokemon("737","Charjabug","Bug","Electric",R.drawable.charjabug,7,"common");
        new Pokemon("738","Vikavolt","Bug","Electric",R.drawable.vikavolt,7,"rare");
        new Pokemon("739","Crabrawler","Fighting",null,R.drawable.crabrawler,7,"common");
        new Pokemon("740","Crabominable","Fighting","Ice",R.drawable.crabominable,7,"superrare");
        new Pokemon("741","Oricorio","Fire","Flying",R.drawable.oricorio,7,"rare");
        new Pokemon("742","Cutiefly","Bug","Fairy",R.drawable.cutiefly,7,"common");
        new Pokemon("743","Ribombee","Bug","Fairy",R.drawable.ribombee,7,"rare");
        new Pokemon("744","Rockruff","Rock",null,R.drawable.rockruff,7,"common");
        new Pokemon("745","Lycanroc","Rock",null,R.drawable.lycanroc,7,"superrare");
        new Pokemon("746","Wishiwashi","Water",null,R.drawable.wishiwashi,7,"rare");
        new Pokemon("747","Mareanie","Poison","Water",R.drawable.mareanie,7,"common");
        new Pokemon("748","Toxapex","Poison","Water",R.drawable.toxapex,7,"superrare");
        new Pokemon("749","Mudbray","Ground",null,R.drawable.mudbray,7,"common");
        new Pokemon("750","Mudsdale","Ground",null,R.drawable.mudsdale,7,"superrare");
        new Pokemon("751","Dewpider","Water","Bug",R.drawable.dewpider,7,"common");
        new Pokemon("752","Araquanid","Water","Bug",R.drawable.araquanid,7,"superrare");
        new Pokemon("753","Fomantis","Grass",null,R.drawable.fomantis,7,"common");
        new Pokemon("754","Lurantis","Grass",null,R.drawable.lurantis,7,"rare");
        new Pokemon("755","Morelull","Grass","Fairy",R.drawable.morelull,7,"common");
        new Pokemon("756","Shiinotic","Grass","Fairy",R.drawable.shiinotic,7,"rare");
        new Pokemon("757","Salandit","Poison","Fire",R.drawable.salandit,7,"common");
        new Pokemon("758","Salazzle","Poison","Fire",R.drawable.salazzle,7,"ultra");
        new Pokemon("759","Stufful","Normal","Fighting",R.drawable.stufful,7,"common");
        new Pokemon("760","Bewear","Normal","Fighting",R.drawable.bewear,7,"rare");
        new Pokemon("761","Bounsweet","Grass",null,R.drawable.bounsweet,7,"common");
        new Pokemon("762","Steenee","Grass",null,R.drawable.steenee,7,"rare");
        new Pokemon("763","Tsareena","Grass",null,R.drawable.tsareena,7,"ultra");
        new Pokemon("764","Comfey","Fairy",null,R.drawable.comfey,7,"rare");
        new Pokemon("765","Oranguru","Normal","Psychic",R.drawable.oranguru,7,"superrare");
        new Pokemon("766","Passimian","Fighting",null,R.drawable.passimian,7,"superrare");
        new Pokemon("767","Wimpod","Bug","Water",R.drawable.wimpod,7,"common");
        new Pokemon("768","Golisopod","Bug","Water",R.drawable.golisopod,7,"ultra");
        new Pokemon("769","Sandygast","Ghost","Ground",R.drawable.sandygast,7,"common");
        new Pokemon("770","Palossand","Ghost","Ground",R.drawable.palossand,7,"superrare");
        new Pokemon("771","Pyukumuku","Water",null,R.drawable.pyukumuku,7,"rare");
        new Pokemon("772","Type: Null","Normal",null,R.drawable.typenull,7,"legend");
        new Pokemon("773","Silvally","Normal",null,R.drawable.silvally,7,"legend");
        new Pokemon("774","Minior","Rock","Flying",R.drawable.minior,7,"superrare");
        new Pokemon("775","Komala","Normal",null,R.drawable.komala,7,"common");
        new Pokemon("776","Turtonator","Fire","Dragon",R.drawable.turtonator,7,"superrare");
        new Pokemon("777","Togedemaru","Electric","Steel",R.drawable.togedemaru,7,"common");
        new Pokemon("778","Mimikyu","Ghost","Fairy",R.drawable.mimikyu,7,"rare");
        new Pokemon("779","Bruxish","Water","Psychic",R.drawable.bruxish,7,"rare");
        new Pokemon("780","Drampa","Normal","Dragon",R.drawable.drampa,7,"superrare");
        new Pokemon("781","Dhelmise","Ghost","Grass",R.drawable.dhelmise,7,"superrare");
        new Pokemon("782","Jangmo-mo","Dragon",null,R.drawable.jangmoo,7,"rare");
        new Pokemon("783","Hakamo-o","Dragon","Flying",R.drawable.hakamoo,7,"superrare");
        new Pokemon("784","Kommo-o","Dragon","Fighting",R.drawable.kommoo,7,"ultra");
        new Pokemon("785","Tapu Koko","Electric","Fairy",R.drawable.tapukoko,7,"legend");
        new Pokemon("786","Tapu Lele","Psychic","Fairy",R.drawable.tapulele,7,"legend");
        new Pokemon("787","Tapu Bulu","Grass","Fairy",R.drawable.tapubulu,7,"legend");
        new Pokemon("788","Tapu Fini","Water","Fairy",R.drawable.tapufini,7,"legend");
        new Pokemon("789","Cosmog","Psychic",null,R.drawable.cosmog,7,"legend");
        new Pokemon("790","Cosmoem","Psychic",null,R.drawable.cosmoem,7,"legend");
        new Pokemon("791","Solgaleo","Psychic","Steel",R.drawable.solgaleo,7,"legend");
        new Pokemon("792","Lunala","Psychic","Ghost",R.drawable.lunala,7,"legend");
        new Pokemon("793","Nihilego","Rock","Poison",R.drawable.nihilego,7,"legend");
        new Pokemon("794","Buzzwole","Bug","Fighting",R.drawable.buzzwole,7,"legend");
        new Pokemon("795","Pheromosa","Bug","Fighting",R.drawable.pheromosa,7,"legend");
        new Pokemon("796","Xurkitree","Electric",null,R.drawable.xurkitree,7,"legend");
        new Pokemon("797","Celesteela","Steel","Flying",R.drawable.celesteela,7,"legend");
        new Pokemon("798","Kartana","Grass","Steel",R.drawable.kartana,7,"legend");
        new Pokemon("799","Guzzlord","Dark","Dragon",R.drawable.guzzlord,7,"legend");
        new Pokemon("800","Necrozma","Psychic",null,R.drawable.necrozma,7,"legend");
        new Pokemon("801","Magearna","Steel","Fairy",R.drawable.magearna,7,"legend");
        new Pokemon("802","Marshadow","Fighting","Ghost",R.drawable.marshadow,7,"legend");
        new Pokemon("803","Poipole","Poison",null,R.drawable.poipole,7,"ultra");
        new Pokemon("804","Naganadel","Poison","Dragon",R.drawable.naganadel,7,"legend");
        new Pokemon("805","Stakataka","Rock","Steel",R.drawable.stakataka,7,"legend");
        new Pokemon("806","Blacephalon","Fire","Ghost",R.drawable.blacephalon,7,"legend");
        new Pokemon("807","Zeraora","Electric",null,R.drawable.zeraora,7,"legend");
        new Pokemon("808","Meltan","Steel",null,R.drawable.meltan,7,"ultra");
        new Pokemon("809","Melmetal","Steel",null,R.drawable.melmetal,7,"legend");
        new Pokemon("810","Grookey","Grass",null,R.drawable.grookey,8,"rare");
        new Pokemon("811","Thwackey","Grass",null,R.drawable.thwackey,8,"superrare");
        new Pokemon("812","Rillaboom","Grass",null,R.drawable.rillaboom,8,"ultra");
        new Pokemon("813","Scorbunny","Fire",null,R.drawable.scorbunny,8,"rare");
        new Pokemon("814","Raboot","Fire",null,R.drawable.raboot,8,"superrare");
        new Pokemon("815","Cinderace","Fire",null,R.drawable.cinderace,8,"ultra");
        new Pokemon("816","Sobble","Water",null,R.drawable.sobble,8,"rare");
        new Pokemon("817","Drizzile","Water",null,R.drawable.drizzile,8,"superrare");
        new Pokemon("818","Inteleon","Water",null,R.drawable.inteleon,8,"ultra");
        new Pokemon("819","Skwovet","Normal",null,R.drawable.skwovet,8,"common");
        new Pokemon("820","Greedent","Normal",null,R.drawable.greedent,8,"rare");
        new Pokemon("821","Rookidee","Flying",null,R.drawable.rookidee,8,"common");
        new Pokemon("822","Corvisquire","Flying",null,R.drawable.corvisquire,8,"rare");
        new Pokemon("823","Corviknight","Flying","Steel",R.drawable.corviknight,8,"superrare");
        new Pokemon("824","Blipbug","Bug",null,R.drawable.blipbug,8,"common");
        new Pokemon("825","Dottler","Bug","Psychic",R.drawable.dottler,8,"common");
        new Pokemon("826","Orbeetle","Bug","Psychic",R.drawable.orbeetle,8,"rare");
        new Pokemon("827","Nickit","Dark",null,R.drawable.nickit,8,"common");
        new Pokemon("828","Thievul","Dark",null,R.drawable.thievul,8,"rare");
        new Pokemon("829","Gossifleur","Grass",null,R.drawable.gossifleur,8,"common");
        new Pokemon("830","Eldegoss","Grass",null,R.drawable.eldegoss,8,"rare");
        new Pokemon("831","Wooloo","Normal",null,R.drawable.wooloo,8,"common");
        new Pokemon("832","Dubwool","Normal",null,R.drawable.dubwool,8,"superrare");
        new Pokemon("833","Chewtle","Water",null,R.drawable.chewtle,8,"common");
        new Pokemon("834","Drednaw","Water","Rock",R.drawable.drednaw,8,"superrare");
        new Pokemon("835","Yamper","Electric",null,R.drawable.yamper,8,"common");
        new Pokemon("836","Boltund","Electric",null,R.drawable.boltund,8,"superrare");
        new Pokemon("837","Rolycoly","Rock",null,R.drawable.rolycoly,8,"common");
        new Pokemon("838","Carkol","Rock","Fire",R.drawable.carkol,8,"rare");
        new Pokemon("839","Coalossal","Rock","Fire",R.drawable.coalossal,8,"ultra");
        new Pokemon("840","Applin","Grass","Dragon",R.drawable.applin,8,"common");
        new Pokemon("841","Flapple","Grass","Dragon",R.drawable.flapple,8,"rare");
        new Pokemon("842","Appletun","Grass","Dragon",R.drawable.appletun,8,"ultra");
        new Pokemon("843","Silicobra","Ground",null,R.drawable.silicobra,8,"common");
        new Pokemon("844","Sandaconda","Ground",null,R.drawable.sandaconda,8,"superrare");
        new Pokemon("845","Cramorant","Flying","Water",R.drawable.cramorant,8,"rare");
        new Pokemon("846","Arrokuda","Water",null,R.drawable.arrokuda,8,"common");
        new Pokemon("847","Barraskewda","Water",null,R.drawable.barraskewda,8,"superrare");
        new Pokemon("848","Toxel","Electric","Poison",R.drawable.toxel,8,"rare");
        new Pokemon("849","Toxtricity","Electric","Poison",R.drawable.toxtricity,8,"ultra");
        new Pokemon("850","Sizzlipede","Fire","Bug",R.drawable.sizzlipede,8,"common");
        new Pokemon("851","Centiskorch","Fire","Bug",R.drawable.centiskorch,8,"superrare");
        new Pokemon("852","Clobbopus","Fighting",null,R.drawable.clobbopus,8,"common");
        new Pokemon("853","Grapploct","Fighting",null,R.drawable.grapploct,8,"superrare");
        new Pokemon("854","Sinistea","Ghost",null,R.drawable.sinistea,8,"common");
        new Pokemon("855","Polteageist","Ghost",null,R.drawable.polteageist,8,"rare");
        new Pokemon("856","Hatenna","Psychic",null,R.drawable.hatenna,8,"common");
        new Pokemon("857","Hattrem","Psychic",null,R.drawable.hattrem,8,"rare");
        new Pokemon("858","Hatterene","Psychic","Fairy",R.drawable.hatterene,8,"ultra");
        new Pokemon("859","Impidimp","Dark","Fairy",R.drawable.impidimp,8,"common");
        new Pokemon("860","Morgrem","Dark","Fairy",R.drawable.morgrem,8,"rare");
        new Pokemon("861","Grimmsnarl","Dark","Fairy",R.drawable.grimmsnarl,8,"ultra");
        new Pokemon("862","Obstagoon","Dark","Normal",R.drawable.obstagoon,8,"ultra");
        new Pokemon("863","Perrserker","Steel",null,R.drawable.perrserker,8,"rare");
        new Pokemon("864","Cursola","Ghost",null,R.drawable.cursola,8,"superrare");
        new Pokemon("865","Sirfetch'd","Fighting",null,R.drawable.serfetchd,8,"superrare");
        new Pokemon("866","Mr.Rime","Ice","Psychic",R.drawable.mrrime,8,"superrare");
        new Pokemon("867","Runerigus","Ground","Ghost",R.drawable.runerigus,8,"ultra");
        new Pokemon("868","Milcery","Fairy",null,R.drawable.milcery,8,"common");
        new Pokemon("869","Alcremie","Fairy",null,R.drawable.alcremie,8,"rare");
        new Pokemon("870","Falinks","Fighting",null,R.drawable.falinks,8,"common");
        new Pokemon("871","Pincurchin","Electric",null,R.drawable.pincurchin,8,"common");
        new Pokemon("872","Snom","Ice","Bug",R.drawable.snom,8,"common");
        new Pokemon("873","Frosmoth","Ice","Bug",R.drawable.frosmoth,8,"rare");
        new Pokemon("874","Stonjourner","Rock",null,R.drawable.stonjourner,8,"superrare");
        new Pokemon("875","Eiscue","Ice",null,R.drawable.eiscue,8,"rare");
        new Pokemon("876","Indeedee","Psychic","Normal",R.drawable.indeedee,8,"rare");
        new Pokemon("877","Morpeko","Electric","Dark",R.drawable.morpeko,8,"common");
        new Pokemon("878","Cufant","Steel",null,R.drawable.cufant,8,"common");
        new Pokemon("879","Copperajah","Steel",null,R.drawable.copperajah,8,"superrare");
        new Pokemon("880","Dracozolt","Electric","Dragon",R.drawable.dracozolt,8,"ultra");
        new Pokemon("881","Arctozolt","Electric","Ice",R.drawable.arctozolt,8,"ultra");
        new Pokemon("882","Dracovish","Water","Dragon",R.drawable.dracovish,8,"ultra");
        new Pokemon("883","Arctovish","Water","Ice",R.drawable.arctovish,8,"ultra");
        new Pokemon("884","Duraludon","Steel","Dragon",R.drawable.duraludon,8,"ultra");
        new Pokemon("885","Dreepy","Dragon","Ghost",R.drawable.dreepy,8,"common");
        new Pokemon("886","Drakloak","Dragon","Ghost",R.drawable.drakloak,8,"rare");
        new Pokemon("887","Dragapult","Dragon","Ghost",R.drawable.dragapult,8,"ultra");
        new Pokemon("888","Zacian","Fairy",null,R.drawable.zacian,8,"legend");
        new Pokemon("889","Zamazenta","Fightin",null,R.drawable.zamazenta,8,"legend");
        new Pokemon("890","Eternatus","Poison","Dragon",R.drawable.eternatus,8,"legend");
    }

}

